# Be sure to restart your server after you modify this file.

# Register your app at https://soundcloud.com/you/apps and copy&paste Client ID and Secret here
client_id: '9ec27a0dcaee2dd4fb6880913e63f0a6'
client_secret: '570a2ee83218591937a046c898129403'

# Your secret key for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
secret_token: 'https://api.soundcloud.com/oauth2/token'

# Replace these defaults with the right values for your competition
# These will only be applied the first time you run `rake db:setup`
competition:
  host: 'Hush Productions'
  title: 'Hush Productions Music Contest'
  intro: 'Enter to win $300 cash prize and be featured in an interview for our website!'
  description: 'In an effort to spark some competition and motivation between up and coming artists, we're holding a music contest. Each contestant may upload an original song, which will appear in a list allowing people to vote for their favorite track. The winner will be decided based on who receives the most votes, so make sure to spread the word to your friends and fans!'
  prizes: '* $300 Cash and an exclusive promotional interview conducted for our website'
  about: 'at sodales.'
  #group: ''
  #rules: ''
  #download: ''
  start_date:
  end_date:
